### ISSUE TITLE
Polished Published Thumbnails

### ISSUE THREAD

**Issue by Angeles-Aaron-BSIT32E3** [BSIT32E3-POPSIK/Video_Streaming#22]

**Comment by Hoshitarou** [comment]
Thumbnails for the videos
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/f82a246e-e1c6-41c0-9b89-24286cf18710)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/f7d68398-91c7-4c8a-8743-8c51ac476111)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/8c91da95-6a7c-4e1f-b67f-a50954710740)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/52c9a270-4ec3-4552-80be-0b7cdd8cdb92)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/54defd01-cd99-431a-aaee-dc1608544fd9)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/5674a309-f263-4e8e-a581-2f4d116d3819)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/67f2fe51-47db-4a6e-8389-90eb1801c85f)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/2db21cdf-92e8-4ce0-971a-d295e93dbf06)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/1ba730c8-0922-4e6f-b4b9-3bbfb2c43a72)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/76e8c2d6-1632-42b3-afc1-8ea7ff59c6dd)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/dd6fb508-4cba-44e8-a4a7-174903a0bc3d)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/2c7a658a-946a-433f-9ba3-fdd77b3eff82)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/b883c2a9-78d3-4ce4-9f63-e8743a6d716e)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/3f7e0e78-af75-4cec-8adc-b98de6ea5984)
![Image](https://github.com/BSIT32E3-POPSIK/Video_Streaming/assets/132931625/31123444-d2af-4b5d-9c7c-c3e4f8b0509d)
